[package]
name = "you-can-build-macros"
description = "ಠ_ಠ"
license = "MIT OR Apache-2.0"
version = "0.0.2021"
edition = "2021"

[lib]
proc-macro = true
path = "./macros.rs"

[dependencies]
bat = "0.19.0"
crossterm = "0.22.1"
eyre = "0.6.6"
prettyplease = "0.1.1"
quote = "1.0.14"
syn = "1.0.85"
