on: [push, workflow_dispatch, pull_request]
name: rust
jobs:
  rust:
    strategy:
      matrix:
        rust_toolchain: ["stable", "nightly"]
        include:
        - rust_toolchain: stable
        - rust_toolchain: beta
          rust_bootstrap: RUSTC_BOOTSTRAP=1
        - rust_toolchain: nightly
      fail-fast: false
    runs-on: ubuntu-latest
    name: "${{ matrix.rust_bootstrap }} ${{ matrix.rust_toolchain }}"
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.rust_toolchain }}
      - run: ${{ matrix.rust_bootstrap }} cargo +${{ matrix.rust_toolchain }} test --all
      - run: ${{ matrix.rust_bootstrap }} cargo +${{ matrix.rust_toolchain }} doc --all
      - run: ${{ matrix.rust_bootstrap }} cargo +${{ matrix.rust_toolchain }} test --examples
        if: ${{ matrix.rust_toolchain }} == 'nightly'

