on: [push, workflow_dispatch, pull_request]
jobs:
  rust:
    strategy:
      matrix:
        rust_toolchain: ["stable", "nightly"]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.rust_toolchain }}
      - run: cargo +${{ matrix.rust_toolchain }} test --all --examples
      - run: cargo +${{ matrix.rust_toolchain }} doc --all
