on: [push, workflow_dispatch, pull_request]
name: rust
jobs:
  rust:
    strategy:
      matrix:
        include:
        - rust_toolchain: stable
          name: stable
          tests: --tests
        - rust_toolchain: beta
          name: unstable beta
          rust_bootstrap: RUSTC_BOOTSTRAP=1
          tests: --all
        - rust_toolchain: nightly
          name: unstable nightly
          tests: --all
      fail-fast: false
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_toolchain }}
      - run: ${{ matrix.rust_bootstrap }} cargo +${{ matrix.rust_toolchain }} build --all
      - run: ${{ matrix.rust_bootstrap }} cargo +${{ matrix.rust_toolchain }} clean
      - run: ${{ matrix.rust_bootstrap }} cargo +${{ matrix.rust_toolchain }} test ${{ matrix.tests }}
      - run: ${{ matrix.rust_bootstrap }} cargo +${{ matrix.rust_toolchain }} doc --all
